### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by MarioProjects** [wisepaip/paip2020#1]
Hi, first of all thanks for your work!

I am new with this type of data and is difficult for me. I have used https://github.com/wisepaip/paip2020/blob/master/xml2mask.py to take the masks on this year challenge and generated masks said that have for example 3 regions (https://github.com/wisepaip/paip2020/blob/master/xml2mask.py#L46). Using the pyslide library and examples for read WSI, as wsi_head.read_region((0, 0), DISPLAY_LEVEL, wsi_head.level_dimensions[DISPLAY_LEVEL]) I can load de wsi at desired level but I dont know what means 0,0 region... When I train my network I should use 0,0 region or? I load the mask as provided https://github.com/paip-2019/challenge/blob/master/utils.py#L9 but I no see nothing related to regions...

Best regards

**Comment by hjoonjang** [comment]
Hi, thanks for taking part in our challenge. We understand that there are many difficulties you might have been through with the histopathology slides dataset.

Though I think I didn't clearly & fully get what you meant, first of all, you seem to ask us the semantics of `read_region` method of `pyslide` library (probably from [here](https://github.com/PingjunChen/pyslide/blob/64fb2a6f8a108f3d74a19905875da2e4aa307638/pyslide/pyramid/_pyramid.py#L94)). That is from `OpenSlide` library so I would like to suggest you search the exact method [here](https://openslide.org/api/python/#openslide.OpenSlide.read_region).

In the next scope, assuming that you had correctly generated masks with the same scales to that of WSIs you wanted to check, I still think you would not miss what the mask is representing. Could you please elaborate on your question a little bit more?

FYI, you can find a handy WSI viewer ASAP [here](https://github.com/computationalpathologygroup/ASAP) just with `*.svs` and `*.xml` to have a quick check of what they look like.

**Comment by MarioProjects** [comment]
Yea I was not too much clear sorry.

My principal doubt is: what is a region? I saw some posts about SWI images like https://ysbecca.github.io/programming/2018/05/22/py-wsi.html and I have clear now what are levels and tiles but no regions, or better, how I should use them.

For that challenge what I understand and I pretend to load the data is loading the WSI and mask files, taking level 2 (as the predictions probably will in that level), and splitting them in patches, the typical approach. For me is clearer to follow the approach described here https://github.com/PingjunChen/LiverCancerSeg/blob/master/seg/pred_test_slide.py, that is for test, but I will use it for train too because is easy to follow for now. With this I should conclude the train of the model but I cant see where 'regions' come to place in this approach, since in this scripts they take (0,0)... Following the xml2mask script provided here to extract level 2 masks, when I load I have images like (height, width, channels), should I do something with the regions?

Thanks for all! I tried to be more clear but sorry If is hard to understand.

**Comment by hjoonjang** [comment]
I meant nothing special with `region` keyword, unlike `levels` and `tiles`, it is a kind of common word so you can alternatively use `patch coordinates`, `area`, `sub-image`, or so. I guess it might be the shortcut for you to take `pyslide` you've mentioned.

Giving Level2 option is no more than the merely default setting because you will submit the prediction results on that scale due to the logistic issues of the Grand-challenge platform. This scale is neither 'typical' nor 'gold-standard'. In other words, there is no such constraint that you should only use level2 images from WSI for training.

Plus, about '(0,0)' of `read_region` method, please carefully read the original usage I showed you in the last comment ([here](https://openslide.org/api/python/#openslide.OpenSlide.read_region)). '(0,0)' is just a starting point, and there is a `SIZE` parameter. After you take images from WSIs with any kind of library (probably with `pyslide`), the image you get must be in the format of (height, width, channels), but it's usually too big to load on a single GPU. You may need some preprocessing before loading on GPUs, I guess.

Hope this helps,
Thanks.

**Comment by MarioProjects** [comment]
Thanks! Is not clear for me at all what regions are because I 'can't see them' inspecting with numpy or so, but I will investigate with your link/info.
