### ISSUE TITLE
Mask files are all black

### ISSUE THREAD

**Issue by stevenjayfrank** [wisepaip/paip2020#2]
Really appreciate your posting this utility.  But when I run it, all of generated tif files are completely black.  Any suggestions very much appreciated.

**Comment by hjoonjang** [comment]
Hi, @stevenjayfrank 

I've tested right away but found nothing wrong. I guess that's because you might have checked the masks without any colormaps. Since the resulting masks have [0 or 1] values within the [0, 255] 8-bit unsigned integer range, if you would like to check them easier with any viewer, either of the below will be required:
- line 91 ([here](https://github.com/wisepaip/paip2020/blob/5a5f3a9c82e0278a818926277133e83b68aa4283/xml2mask.py#L91)) should be
`tifffile.imsave(save_fn, (ret[1]>0).astype(np.uint8) * 255, compress=9)`
- certain kind of qualitative colormap should be applied (e.g. if you're using Fiji, I recommend `glasbey_on_dark` option in LUT drop menu.)

If you still are on the same page after trying the abovementioned, please let us know again.

Thanks!

**Comment by stevenjayfrank** [comment]
Thank you, that's very helpful, now I can see the mask contours.  I am new to Fiji -- how can I apply the mask to the slide to view the XML annotation for the tumor area as multiple closed areas defined by the colored line?  Sorry, I know this is a very basic question.

**Comment by hjoonjang** [comment]
Can you tell me which slide has such multiple color annotations? In our dataset of this challenge, there may not be any 'meaningfully distinguishable' layers, so I'll double-check if there is.

As an answer with general recommendations, as far as I know, the most straight-forward way is to apply code-level preprocessing. Please load them on memory with any programming language you're familiar with, and then you will be able to overlay the two (WSI and mask).

**Comment by stevenjayfrank** [comment]
Sorry, I was quoting from the PAIP2020 Dataset page [here](https://paip2020.grand-challenge.org/Dataset/), which shows an example annotated slide with the tumor surrounded by a colored line.  I assume there is some way to generate that from the .svs files and the .xml files we download.

**Comment by stevenjayfrank** [comment]
Yes, definitely much easier to code :)

![image](https://user-images.githubusercontent.com/51024412/80315761-a7b32a80-87c7-11ea-9690-cce23ccd7985.png)
